# Generated by Django 2.2.24 on 2023-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='authorusername',
            field=models.CharField(default='default_username', max_length=255),
        ),
    ]
