# Generated by Django 4.2.5 on 2023-09-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_postarticle_authorusername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postarticle",
            name="authorusername",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="postarticle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
